services:
  api:
    build:
      context: ./BikeRoutesApi
      target: final
    ports:
      - "5043:8080"
    container_name: bikeroutes_api
    hostname: bikeroutes_api_host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development